[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/og-image.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[build]
  publish = "."